### ISSUE TITLE
Overlay HUD

### ISSUE THREAD

**Issue by totallynothenry** [cmu15466-gsilvera/OrbitalPhysics#14]
Something things we probably want: (feel free to change)

- [x] thrust level [vertical gauge from 0 to 100, with a sliding bar indicating current level]
- [ ] fuel remaining
- [ ] Time dilation level [horizontal gauge with fixed increments (KSP uses triangles that light up for reference)]
- [ ] Heading
- [ ] Prograde (direction of orbit, a.k.a the direction `orbit->rvel` points, retrograde (opposite of prograde)
- [ ] vectors perpendicular to prograde: radial in (toward body being orbited) / radial out (away from body being orbited)
- [ ] Recolor orbits to be easier to see and more clear which is which
- [ ] Autopilot system that snaps to prograde, retrograde, radial in, radial out, etc. Need on-screen buttons (preferably) or keyboard mappings for each of these.
- [ ] direction toward asteroid
- [ ] direction away from asteroid
- [x] when zoomed out too far (i.e. when camera arm is X times the radius of the asteroid/rocket), use a simple marker to indicate where the asteroid/rocket is. Can be anything from a colored circle to a sprite.

**Comment by totallynothenry** [comment]
Since we're short on time, I think we might just want to draw the vectors in a little box on the lower left corner of the screen.

**Comment by GustavoSilvera** [comment]
Addressing the simple marker (when camera zoomed out enough) with [this commit](https://github.com/cmu15466-gsilvera/OrbitalPhysics/commit/a07f6c905e7d8ba5a509bffe6f922010b1f1938e)
